### ISSUE TITLE
Zinger internal exception when only one exploration path exists and -ct switch is used

### ISSUE THREAD

**Issue by rahul-ramadas** [ZingModelChecker/Zing#2]
Zinger throws an internal exception when there is an assert in a program that has a single exploration path. This exception manifests only when the `-ct` switch is used.

Minimal program with which you can reproduce the problem:

```
class TraceCompactionExceptionRepro
{
    activate static void Main()
    {
        int testVal;
        testVal = 0;

        assert(testVal == 1, "Zing crash!");
    }
};
```

Instead of failing with an assert, Zinger crashes.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Zing.FrontierNode.GetTraversalInfoForTrace(Trace trace, Int32 threadId, StateImpl iState) in E:\Zing\Microsoft.Zing.Runtime\FrontierTree.cs:line 539
   at Microsoft.Zing.FrontierNode.GetTraversalInfo(StateImpl InitialState, Int32 threadId) in E:\Zing\Microsoft.Zing.Runtime\FrontierTree.cs:line 453
   at Microsoft.Zing.ZingExplorerExhaustiveSearch.SearchStateSpace(Object obj) in E:\Zing\ZingExplorer\ZingExplorerExhaustiveSearch.cs:line 102
   at System.Threading.Tasks.Task.Execute()
Zinger Internal Runtime Exception
0 distinct states explored
```

**Comment by rahul-ramadas** [comment]
Was this fixed?
