### ISSUE TITLE
Issue with COmega

### ISSUE THREAD

**Issue by teja5832** [ZingModelChecker/Zing#5]
I've tried to run Zing as well as ZC on a Developer Command Prompt for VS, and get the following runtime error:

COmega problem
.\zc.exe : 
At line:1 char:1
- .\zc.exe C:\Users\teja5832\Desktop\n-bt.zing 2>&1 >> C:\Users\teja583 ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:String) [], RemoteException
  - FullyQualifiedErrorId : NativeCommandError

Unhandled Exception: 
System.TypeInitializationException: The type initializer for 'Microsoft.Comega.Runtime' threw an exception. ---> 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Comega.Runtime.Initialize() in C:\cci\microsoft.comega\Runtime.cs:line 187
   at Microsoft.Comega.Runtime..cctor() in C:\cci\microsoft.comega\Runtime.cs:line 167
   --- End of inner exception stack trace ---
   at Microsoft.Comega.Compiler.AddStandardLibraries(CompilerOptions coptions, Module module, TrivialHashtable 
alreadyReferencedAssemblies) in C:\cci\microsoft.comega\Compiler.cs:line 216
   at System.Compiler.Compiler.CreateModule(CompilerParameters options, ErrorNodeList errorNodes, Compilation 
compilation) in C:\cci\System.Compiler.Framework\Compiler\Compiler.cs:line 1184
   at System.Compiler.Compiler.CreateModule(CompilerParameters options, ErrorNodeList errorNodes) in 
C:\cci\System.Compiler.Framework\Compiler\Compiler.cs:line 1140
   at Microsoft.Zing.Templates.CompileTemplate(String templateName, Object[] additionalDefines) in 
D:\Root\ZING\src.V1\Microsoft.Zing\Splicer.cs:line 2599
   at Microsoft.Zing.Templates.InitializeTemplates() in D:\Root\ZING\src.V1\Microsoft.Zing\Splicer.cs:line 2522
   at Microsoft.Zing.Splicer.CodeGen(Compilation compilation) in D:\Root\ZING\src.V1\Microsoft.Zing\Splicer.cs:line 108
   at Microsoft.Zing.Compiler.CompileParseTree(Compilation compilation, ErrorNodeList errorNodes) in 
D:\Root\ZING\src.V1\Microsoft.Zing\compiler.cs:line 231
   at Microsoft.Zing.Compiler.CompileAssemblyFromFileBatch(CompilerParameters options, String[] fileNames, 
ErrorNodeList errorNodes, Boolean canUseMemoryMap) in D:\Root\ZING\src.V1\Microsoft.Zing\compiler.cs:line 179
   at System.Compiler.Compiler.CompileAssemblyFromFile(CompilerParameters options, String fileName, ErrorNodeList 
errorNodes, Boolean canUseMemoryMap) in C:\cci\System.Compiler.Framework\Compiler\Compiler.cs:line 137
   at System.Compiler.Compiler.CompileAssemblyFromFile(CompilerParameters options, String fileName, ErrorNodeList 
errorNodes) in C:\cci\System.Compiler.Framework\Compiler\Compiler.cs:line 133
   at System.Compiler.Compiler.CompileAssemblyFromFile(CompilerParameters options, String fileName) in 
C:\cci\System.Compiler.Framework\Compiler\Compiler.cs:line 58
   at main.Main(String[] args) in D:\Root\ZING\src.V1\zc\Main.cs:line 73

I'm running this on Win10(Bootcamp) and VS 2015. I could find no means to install COmega directly as well. I need this to test the P framework.

Thanks!

Teja

**Comment by ankushdesai** [comment]
Can you make sure that your system has .Net 3.5 installed ?

**Comment by teja5832** [comment]
Installed .NET 3.5 and it works. Thank you!
